language: go
go:
  - 1.13.x

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

before_install:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - go get -u github.com/mattn/goveralls
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
  - gcloud components install cloud-datastore-emulator beta

before_script:
  - gcloud beta emulators datastore start &
  # sleep until this file exists, that should mean the emulator is running
  - while [ ! -f /home/travis/.config/gcloud/emulators/datastore/env.yaml ]; do sleep 1; done;
  - $(gcloud beta emulators datastore env-init)

script:
  - golangci-lint run ./...
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service=travis-ci
