runtime: go113

main: ./cmd/server

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /static
    static_dir: frontend/build/static
    secure: always

  - url: /(.*\.(json|ico|js))$
    static_files: frontend/build/\1
    upload: frontend/build/.*\.(json|ico|js)$
    secure: always

  - url: .*
    static_files: frontend/build/index.html
    upload: frontend/build/index.html
    secure: always

# include env.yaml based on what's in README
includes:
  - env.yaml