runtime: go113

main: ./cmd/server

handlers:
  - url: /
    static_files: frontend/build/index.html
    upload: frontend/build/index.html
    secure: always

  - url: /(.+)
    static_files: frontend/build/\1
    upload: frontend/build/(.+)
    secure: always

  - url: /api/.*
    script: auto
    secure: always

# include env.yaml based on what's in README
includes:
  - env.yaml